import * as fs from 'fs';
import * as path from 'path';
import type { CodexEntry } from '@/types/codex';

/**
 * Server-only access to the compiled codex (data/codex/compiled.json).
 * Generated by scripts/build-codex.mts from content/codex/entities/*.md — never hand-edit it.
 * Read with fs (not import) so the multi-MB blob stays out of the client bundle and is cached once.
 * The codex navigates by relation, so this is a flat id index — there is no category tree.
 */
interface Compiled {
  byId: Record<string, CodexEntry>;
}

let cache: Compiled | null = null;
let cacheMtimeMs = 0;

function load(): Compiled {
  const file = path.join(process.cwd(), 'data/codex/compiled.json');
  // In dev, re-read when the file's mtime has advanced so the page reflects the
  // latest `build-codex` output without a server restart. Next.js doesn't watch
  // JSON data files, so without this the module-level cache pins a stale snapshot
  // for the lifetime of the dev process. In prod, build the cache once and trust it.
  if (process.env.NODE_ENV !== 'production') {
    const mtimeMs = fs.statSync(file).mtimeMs;
    if (!cache || mtimeMs !== cacheMtimeMs) {
      cache = JSON.parse(fs.readFileSync(file, 'utf8')) as Compiled;
      cacheMtimeMs = mtimeMs;
    }
    return cache;
  }
  if (!cache) {
    cache = JSON.parse(fs.readFileSync(file, 'utf8')) as Compiled;
  }
  return cache;
}

export function getEntryById(id: string): CodexEntry | undefined {
  return load().byId[id];
}

/**
 * Every entry carrying `tag`, matched case-insensitively. Case folding also
 * merges the data's accidental casing duplicates (e.g. "yolus breach" vs
 * "Yolus breach") into one list. Unsorted — callers order for display.
 */
export function getEntriesByTag(tag: string): CodexEntry[] {
  const needle = tag.toLowerCase();
  return Object.values(load().byId).filter((e) =>
    e.tags?.some((t) => t.toLowerCase() === needle)
  );
}

/** Resolve a list of entity ids to {id, name}, dropping any that no longer exist. */
export function resolveRefs(ids: string[] | undefined): { id: string; name: string }[] {
  if (!ids?.length) return [];
  const { byId } = load();
  return ids
    .map((id) => byId[id])
    .filter((e): e is CodexEntry => Boolean(e))
    .map((e) => ({ id: e.id, name: e.name }));
}
