import * as fs from 'fs';
import * as path from 'path';
import type { CodexEntry } from '@/types/codex';

/**
 * Server-only access to the compiled codex (data/codex/compiled.json).
 * Generated by scripts/build-codex.mts from content/codex/entities/*.md — never hand-edit it.
 * Read with fs (not import) so the multi-MB blob stays out of the client bundle and is cached once.
 * The codex navigates by relation, so this is a flat id index — there is no category tree.
 */
interface Compiled {
  byId: Record<string, CodexEntry>;
}

let cache: Compiled | null = null;

function load(): Compiled {
  if (!cache) {
    const file = path.join(process.cwd(), 'data/codex/compiled.json');
    cache = JSON.parse(fs.readFileSync(file, 'utf8')) as Compiled;
  }
  return cache;
}

export function getEntryById(id: string): CodexEntry | undefined {
  return load().byId[id];
}

/** Resolve a list of entity ids to {id, name}, dropping any that no longer exist. */
export function resolveRefs(ids: string[] | undefined): { id: string; name: string }[] {
  if (!ids?.length) return [];
  const { byId } = load();
  return ids
    .map((id) => byId[id])
    .filter((e): e is CodexEntry => Boolean(e))
    .map((e) => ({ id: e.id, name: e.name }));
}
