#!/usr/bin/env bash
# Headless dev server manager — generated by /grove:headless
# Edit the "Project-specific dispatch" section below; the utilities above are reusable.

set -uo pipefail

# ─── Log directory (grove-instance-safe) ─────────────────────────────────────
# Path slug ensures two instances on disk get separate log dirs.

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SLUG="$(echo "$REPO_ROOT" | sed 's|^/||; s|/|-|g')"
LOG_DIR="/tmp/grove/${SLUG}"
mkdir -p "$LOG_DIR"

log_path() { echo "${LOG_DIR}/$1-dev.log"; }

# ─── Process & port utilities ────────────────────────────────────────────────

wait_for_port_free() {
    local port=$1 i=0
    while lsof -i :$port -sTCP:LISTEN >/dev/null 2>&1 && [ $i -lt 20 ]; do
        sleep 0.5; i=$((i + 1))
    done
    [ $i -lt 20 ]
}

kill_on_port() {
    local pid=$(lsof -i :$1 -sTCP:LISTEN -t 2>/dev/null)
    if [ -n "$pid" ]; then
        kill $pid 2>/dev/null
        wait_for_port_free "$1" || kill -9 $pid 2>/dev/null
        wait_for_port_free "$1"
    fi
}

kill_process_tree() {
    local pid=$1
    kill -- -$(ps -o pgid= -p $pid | tr -d ' ') 2>/dev/null || kill $pid 2>/dev/null
    pkill -P $pid 2>/dev/null
}

# Returns "free", "ours:<pid>", or "other".
# Checks the pid AND its parent — some dev servers (next-server) don't show the repo path
# in their own argv but their pnpm/npm parent does. Missing this causes false "other" verdicts
# and grove instances refusing to start services they actually own.
port_status() {
    local port=$1 dir=$2
    local pid=$(lsof -i :${port} -sTCP:LISTEN -t 2>/dev/null | head -1)
    if [ -z "$pid" ]; then echo "free"; return; fi
    local pattern="${REPO_ROOT}/${dir}"
    local ppid=$(ps -o ppid= -p "$pid" 2>/dev/null | tr -d ' ')
    if ps -o command= -p "$pid" 2>/dev/null | grep -q "$pattern" || \
       { [ -n "$ppid" ] && ps -o command= -p "$ppid" 2>/dev/null | grep -q "$pattern"; }; then
        echo "ours:$pid"
    else
        echo "other"
    fi
}

kill_service_processes() {
    local scoped="${REPO_ROOT}/$1"
    for pid in $(pgrep -f "${scoped}.*pnpm.*dev" 2>/dev/null) \
               $(pgrep -f "${scoped}.*npm.*dev" 2>/dev/null) \
               $(pgrep -f "${scoped}.*pnpm.*start:dev" 2>/dev/null) \
               $(pgrep -f "${scoped}.*next.*dev" 2>/dev/null) \
               $(pgrep -f "${scoped}/node_modules/.bin" 2>/dev/null); do
        kill_process_tree "$pid"
    done
    sleep 0.5
}

stop_service() {
    local dir=$1 port=$2
    kill_service_processes "$dir"
    kill_on_port "$port"
}

# Supervised restart with exponential backoff + port health watchdog.
# - Process crash: detected via wait, restarted with backoff
# - Zombie process (alive but port dead): watchdog kills after 30s, triggers restart
# - TERM=dumb prevents tsc --watch from emitting clear-screen sequences / null bytes
start_service() {
    local dir=$1 cmd=$2 log=$3 port=${4:-} max_retries=${5:-5}
    nohup bash -c '
        trap "cleanup" TERM INT
        dir="$1"; cmd="$2"; max_retries="$3"; port="$4"
        backoff=2; max_backoff=60; stable_threshold=30; retries=0
        child_pid=""; watchdog_pid=""

        cleanup() {
            [ -n "$watchdog_pid" ] && kill "$watchdog_pid" 2>/dev/null
            [ -n "$child_pid" ] && kill "$child_pid" 2>/dev/null
            exit 0
        }

        while true; do
            start_time=$(date +%s)
            echo "[$(date "+%Y-%m-%d %H:%M:%S")] START: $cmd (attempt $((retries + 1)))"
            (cd "$dir" && TERM=dumb eval "$cmd") &
            child_pid=$!

            if [ -n "$port" ]; then
                _wd_child=$child_pid; _wd_port=$port
                (
                    sleep 60
                    fail_count=0
                    while kill -0 "$_wd_child" 2>/dev/null; do
                        if lsof -i :"$_wd_port" -sTCP:LISTEN >/dev/null 2>&1; then
                            fail_count=0
                        else
                            fail_count=$((fail_count + 1))
                            if [ "$fail_count" -ge 6 ]; then
                                echo "[$(date "+%Y-%m-%d %H:%M:%S")] WATCHDOG: port $_wd_port unresponsive for 30s — killing pid $_wd_child"
                                kill "$_wd_child" 2>/dev/null
                                sleep 2
                                kill -0 "$_wd_child" 2>/dev/null && kill -9 "$_wd_child" 2>/dev/null
                                break
                            fi
                        fi
                        sleep 5
                    done
                ) &
                watchdog_pid=$!
            fi

            wait "$child_pid" 2>/dev/null
            exit_code=$?
            child_pid=""
            [ -n "$watchdog_pid" ] && kill "$watchdog_pid" 2>/dev/null; watchdog_pid=""

            run_duration=$(( $(date +%s) - start_time ))
            if [ "$run_duration" -ge "$stable_threshold" ]; then
                backoff=2; retries=0
            else
                retries=$((retries + 1))
            fi
            echo "[$(date "+%Y-%m-%d %H:%M:%S")] EXITED: code=$exit_code ran=${run_duration}s (retry $retries/$max_retries)"
            if [ "$retries" -ge "$max_retries" ]; then
                echo "[$(date "+%Y-%m-%d %H:%M:%S")] GAVE UP: $max_retries consecutive fast crashes (< ${stable_threshold}s each)"
                break
            fi
            echo "[$(date "+%Y-%m-%d %H:%M:%S")] RESTART: in ${backoff}s..."
            sleep "$backoff"
            backoff=$(( backoff * 2 > max_backoff ? max_backoff : backoff * 2 ))
        done
    ' _ "$dir" "$cmd" "$max_retries" "$port" > "$log" 2>&1 &
}

# Start a service only if its port is free (or already ours).
ensure_service() {
    local name=$1 dir=$2 port=$3 cmd=$4
    local status=$(port_status "$port" "$dir")
    case "${status%%:*}" in
        free)
            kill_service_processes "$dir"
            echo "Starting $name → $(log_path "$name")"
            start_service "${REPO_ROOT}/${dir}" "$cmd" "$(log_path "$name")" "$port"
            ;;
        ours)  echo "✓ $name already on :${port}" ;;
        other) echo "⚠ Port ${port} in use by another environment — skipping $name" ;;
    esac
}

read_env_port() {
    # read_env_port <subdir> <VAR_NAME> <default>
    local subdir=$1 var=$2 default=$3
    local port=$(grep -m1 "^${var}=" "${REPO_ROOT}/${subdir}/.env" 2>/dev/null | cut -d= -f2 | tr -d '"'"'"' ')
    echo "${port:-$default}"
}

ARGS="$*"

echo "Logs: $LOG_DIR"

# ─── Project-specific dispatch ───────────────────────────────────────────────
# Single Next.js app at repo root.
#   alias: web
#   dir:   .
#   port:  read from ./.env as PORT, default 3000 (next dev respects PORT env)
#   cmd:   pnpm dev (next dev reads PORT from environment)

WEB_PORT=$(read_env_port "." PORT 3000)

should_run() {
    [[ "$ARGS" =~ all ]] || ! [[ "$ARGS" =~ web ]] || [[ "$ARGS" =~ $1 ]]
}

# Default to "all" when no service named
if [ -z "$ARGS" ] || [[ "$ARGS" =~ ^(stop|restart)$ ]]; then
    ARGS="${ARGS} all"
fi

if [[ "$ARGS" =~ stop|restart ]]; then
    if should_run web; then
        echo "Stopping web (port $WEB_PORT)..."
        stop_service "." "$WEB_PORT"
    fi
    [[ "$ARGS" =~ ^[[:space:]]*stop ]] && exit 0
fi

if should_run web; then
    ensure_service "web" "." "$WEB_PORT" "PORT=$WEB_PORT pnpm dev"
fi
