/**
 * Re-run the rule-based suggestType() over every PENDING entry in work-queue.json.
 *
 * Why: data/work-queue.json was generated by an older extractor that produced types
 * like 'landmark', 'dungeon', 'temple' which are no longer in LocationType. The pin UI
 * maps these to 'poi' via LEGACY_TYPE_MAP, so e.g. "Shrieking Peaks" (tag=mountains)
 * shows as poi instead of wilderness.
 *
 * Only mutates suggestedType on entries with status='pending'. Pinned and skipped
 * entries are not touched (their stored type is what's on the map / what the user
 * already decided).
 *
 * Backs up data/work-queue.json before mutating.
 */

import * as fs from 'fs';
import * as path from 'path';
import type { LocationType } from '../src/types/location';
import type { LoreEntry, WorkQueue } from '../src/types/pinning';

const ROOT = path.resolve(__dirname, '..');
const WORK_QUEUE = path.join(ROOT, 'data/work-queue.json');
const BACKUP_DIR = path.join(ROOT, 'data/backups');

// Mirror of TAG_TYPE_MAP from extract-locations.ts (only valid LocationType values)
const TAG_TYPE_MAP: Record<string, LocationType> = {
  sea: 'water', ocean: 'water', lake: 'water', river: 'water',
  bay: 'water', strait: 'water', water: 'water',

  dungeon: 'poi', crypt: 'poi', lair: 'poi', tomb: 'poi',
  cavern: 'poi', catacomb: 'poi',

  ruins: 'ruins', ruin: 'ruins', abandoned: 'ruins', ancient: 'ruins',

  fortress: 'fortress', fort: 'fortress', castle: 'fortress',
  stronghold: 'fortress', military: 'fortress',

  temple: 'poi', shrine: 'poi', magical: 'poi', portal: 'poi', sacred: 'poi',

  city: 'city', capital: 'city', citystate: 'city', metropolis: 'city',

  settlement: 'town', village: 'town', town: 'town',
  hamlet: 'town', outpost: 'town',

  forest: 'wilderness', jungle: 'wilderness', swamp: 'wilderness',
  rainforest: 'wilderness', woods: 'wilderness',

  mountains: 'wilderness', mountain: 'wilderness', hills: 'wilderness',
  plains: 'wilderness', desert: 'wilderness', cliffs: 'wilderness',
  canyon: 'wilderness', valley: 'wilderness', peaks: 'wilderness',

  state: 'region', nation: 'region', region: 'region',
  island: 'region', archipelago: 'region', continent: 'region',

  poi: 'poi',
};

const CONTENT_PATTERNS: Array<[RegExp, LocationType]> = [
  [/\b(temple|shrine|sacred|holy|divine|altar)\b/i, 'poi'],
  [/\b(ruins?|ancient|abandoned|crumbl|decay|fallen)\b/i, 'ruins'],
  [/\b(dungeon|crypt|tomb|lair|cavern|catacomb)\b/i, 'poi'],
  [/\b(fortress|castle|fort|stronghold|citadel|keep)\b/i, 'fortress'],
  [/\b(capital|metropolis|great city)\b/i, 'city'],
  [/\b(village|hamlet|settlement|small town)\b/i, 'town'],
  [/\b(forest|jungle|swamp|marsh|woods|grove)\b/i, 'wilderness'],
  [/\b(mountain|peak|hill|canyon|valley|cliff|ridge)\b/i, 'wilderness'],
  [/\b(sea|ocean|lake|river|bay|strait|gulf|waters)\b/i, 'water'],
];

function suggestType(entry: { tags: string[]; contentPreview: string; headerLevel: number }): LocationType {
  const { tags, contentPreview, headerLevel } = entry;

  for (const tag of tags) {
    const lowerTag = tag.toLowerCase();
    if (TAG_TYPE_MAP[lowerTag]) return TAG_TYPE_MAP[lowerTag];
  }

  for (const [pattern, type] of CONTENT_PATTERNS) {
    if (pattern.test(contentPreview)) return type;
  }

  if (headerLevel <= 2) return 'region';
  if (headerLevel === 3) return 'city';
  if (headerLevel === 4) return 'town';
  return 'poi';
}

function ts(): string {
  return new Date().toISOString().replace(/[:.]/g, '-');
}

function main() {
  const queue: WorkQueue = JSON.parse(fs.readFileSync(WORK_QUEUE, 'utf-8'));

  fs.mkdirSync(BACKUP_DIR, { recursive: true });
  fs.copyFileSync(WORK_QUEUE, path.join(BACKUP_DIR, `work-queue.${ts()}.json`));

  // Track changes for the report
  const transitions = new Map<string, number>(); // "old → new" → count
  let changed = 0;
  let unchanged = 0;
  const sampleByTransition = new Map<string, LoreEntry[]>();

  for (const e of queue.entries) {
    if (e.status !== 'pending') continue;
    const next = suggestType(e);
    if (next === e.suggestedType) {
      unchanged++;
      continue;
    }
    const key = `${e.suggestedType} → ${next}`;
    transitions.set(key, (transitions.get(key) ?? 0) + 1);
    const samples = sampleByTransition.get(key) ?? [];
    if (samples.length < 3) {
      samples.push(e);
      sampleByTransition.set(key, samples);
    }
    e.suggestedType = next;
    changed++;
  }

  fs.writeFileSync(WORK_QUEUE, JSON.stringify(queue, null, 2));

  console.log('Type refresh summary:');
  console.log(`  pending entries scanned: ${changed + unchanged}`);
  console.log(`  unchanged: ${unchanged}`);
  console.log(`  changed:   ${changed}`);
  console.log('');
  console.log('Transitions:');
  const sorted = [...transitions.entries()].sort((a, b) => b[1] - a[1]);
  for (const [key, count] of sorted) {
    console.log(`  ${key}: ${count}`);
    const samples = sampleByTransition.get(key) ?? [];
    for (const s of samples) {
      console.log(`    e.g. "${s.name}" (${s.sourceFile}:${s.lineNumber})`);
    }
  }
}

main();
